flowchart TD
    A[RIT] --> B[Administrator]
    A --> C[Evaluator]
    B --> D[PC]
    C --> D
    D --> E[Co-op Evaluation System]
    E --> F[Server]
    E --> G[PC]
    G --> H[Student]
    G --> I[Employer]