flowchart TD
    A[CAS Login] --> B[Simplicity]
    B --> C[OCES's SQL Server Co-op Registration]
    C --> D[Campus Solutions (SIS) Co-op Feed]
    C --> E[Co-op Placement]
    C --> F[OCES's Co-op Input File]
    
    G[Shibboleth Authentication] --> H[Co-op Evaluation System]
    I[Custom Employer Login] --> H
    H --> J[Co-op Evaluation Database]
    H --> K[Jim's Reporting]
    H --> L[ITS Mail Server]
    J --> H