flowchart TD
    A[ITS DNS/Web Server] -->|connects to| B[Co-op Evaluation System]
    C[ITS Mail Server] -->|connects to| B
    D[Shiboleth] -->|connects to| B
    E[Oracle SQL Database] -->|connects to| B