classDiagram
    class Users
    class ExternalAPIs
    class Client {
        Presentation Layer
        HTML
        AngularJS
        CSS/Sass
        Bootstrap
    }
    class Server {
        Service Layer
        Application Logic Layer
        Domain Model Layer
        Data Access Layer
        Data Mappers
        Data Source Layer
        Oracle Database
    }

    Users --> Client
    ExternalAPIs --> Server
    Client --> Server